# Generated by Django 5.0.4 on 2024-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("crest", models.URLField()),
                ("stadium", models.CharField(max_length=100)),
                ("colors", models.CharField(max_length=50)),
                ("mananger", models.CharField(max_length=100)),
                ("ranking", models.IntegerField()),
                ("played", models.IntegerField()),
                ("points", models.IntegerField()),
                ("lastUpdate", models.DateField(auto_now=True)),
            ],
        ),
    ]
