# Generated by Django 5.0.4 on 2024-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixtures", "0004_fixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="awayTeamScore",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="fixture",
            name="homeTeamScore",
            field=models.IntegerField(null=True),
        ),
    ]
